# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ${PGDATA}:/${PGDATA}
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - ${PGPORT}:${PGPORT}
