# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    env_file: .env.development.local
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      -  ${PGDATA}:/${PGDATA}
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - ${PGPORT}:${PGPORT}
