name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  GIT_REPO_NAME: ${{ github.repository }}
  GIT_COMMIT_BRANCH: ${{ github.ref_name }}
  GIT_COMMIT_SHA: ${{ github.sha }}
on:
  push:
    branches:
      - dev
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Strip Owner Part from GIT_REPO_NAME
        run: echo "GIT_REPO_NAME=${GIT_REPO_NAME##*/}" >> $GITHUB_ENV
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
