name: Continuous deploy

on:
  push:
    branches: [main]

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: testy
        run: echo "${{secrets.AWS_ACCESS_KEY_ID}}" 
      - name: get repo
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test

      - name: Deploy to AWS via serverless
        run: npx serverless